# Generated by Django 4.2.27 on 2025-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
