# Generated by Django 6.0 on 2025-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_options_client_notes_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Гостей'),
        ),
    ]
